# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  squid:
    container_name: squid
    image: baklai/squid:latest
    ports:
      - '3128:3128'
    volumes:
      - './squid:/etc/squid'

version: '3.8'

services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta
    container_name: squid-container
    environment:
      - TZ=UTC
    ports:
      - '3128:3128'
    volumes:
      - /path/to/logs:/var/log/squid
      - /path/to/data:/var/spool/squid
      - /path/to/main/config:/etc/squid/squid.conf
      - /path/to/config/snippet:/etc/squid/conf.d/snippet.conf
